framework:
    notifier:
        texter_transports:
            twilio: '%env(TWILIO_DSN)%'

        chatter_transports:
            slack: 'null://null'

        channel_policy:
            urgent: ['sms']
            high: ['sms']
            medium: ['email']
            low: ['email']

        admin_recipients:
            - { email: admin@example.com }
