translation:
    locales: ['en', 'fr', 'es', 'de', 'it']
    configs:
        app:
            dirs: ['%kernel.project_dir%/translations', '%kernel.project_dir%/templates']
            output_dir: '%kernel.project_dir%/translations'
            excluded_dirs: ['cache', 'log', 'vendor']