<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250401174826 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_1');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_2');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_1');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY booking_ibfk_2');
        $this->addSql('ALTER TABLE booking CHANGE id_event id_event INT DEFAULT NULL, CHANGE id_location id_location INT DEFAULT NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED52B4B97 FOREIGN KEY (id_event) REFERENCES event (id_event)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEE45655E FOREIGN KEY (id_location) REFERENCES location (id_location)');
        $this->addSql('DROP INDEX id_event ON booking');
        $this->addSql('CREATE INDEX IDX_E00CEDDED52B4B97 ON booking (id_event)');
        $this->addSql('DROP INDEX id_location ON booking');
        $this->addSql('CREATE INDEX IDX_E00CEDDEE45655E ON booking (id_location)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_1 FOREIGN KEY (id_event) REFERENCES event (id_event) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_2 FOREIGN KEY (id_location) REFERENCES location (id_location) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY cart_ibfk_1');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY cart_ibfk_1');
        $this->addSql('ALTER TABLE cart CHANGE created_at created_at DATETIME NOT NULL, CHANGE total_price total_price NUMERIC(10, 2) DEFAULT NULL');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX user_id ON cart');
        $this->addSql('CREATE INDEX IDX_BA388B7A76ED395 ON cart (user_id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT cart_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY cart_product_ibfk_1');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY cart_product_ibfk_2');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY cart_product_ibfk_2');
        $this->addSql('ALTER TABLE cart_product ADD id INT AUTO_INCREMENT NOT NULL, CHANGE quantity quantity INT NOT NULL, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT FK_2890CCAA1AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (cart_id)');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT FK_2890CCAA4584665A FOREIGN KEY (product_id) REFERENCES product (product_id)');
        $this->addSql('DROP INDEX product_id ON cart_product');
        $this->addSql('CREATE INDEX IDX_2890CCAA4584665A ON cart_product (product_id)');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT cart_product_ibfk_2 FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX code_promo ON code_promo');
        $this->addSql('ALTER TABLE code_promo CHANGE code_promo code_promo VARCHAR(255) NOT NULL, CHANGE date_creation date_creation DATETIME NOT NULL');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_2');
        $this->addSql('ALTER TABLE comments CHANGE content content LONGTEXT NOT NULL, CHANGE comment_date comment_date DATETIME NOT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A38B217A7 FOREIGN KEY (publication_id) REFERENCES publications (publication_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX publication_id ON comments');
        $this->addSql('CREATE INDEX IDX_5F9E962A38B217A7 ON comments (publication_id)');
        $this->addSql('DROP INDEX id_user ON comments');
        $this->addSql('CREATE INDEX IDX_5F9E962A6B3CA4B ON comments (id_user)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publications (publication_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_2 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY event_ibfk_1');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY event_ibfk_1');
        $this->addSql('ALTER TABLE event CHANGE id_user id_user INT DEFAULT NULL, CHANGE description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA76B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX id_user ON event');
        $this->addSql('CREATE INDEX IDX_3BAE0AA76B3CA4B ON event (id_user)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT event_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE location CHANGE city city VARCHAR(255) NOT NULL, CHANGE status status VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE dimension dimension VARCHAR(255) NOT NULL, CHANGE price price NUMERIC(10, 0) NOT NULL, CHANGE has_3d_tour has_3d_tour TINYINT(1) DEFAULT NULL, CHANGE table_set_count table_set_count INT DEFAULT NULL, CHANGE include_corner_plants include_corner_plants TINYINT(1) DEFAULT NULL, CHANGE window_style window_style VARCHAR(255) DEFAULT NULL, CHANGE door_style door_style VARCHAR(255) DEFAULT NULL, CHANGE include_ceiling_lights include_ceiling_lights TINYINT(1) DEFAULT NULL, CHANGE light_color light_color VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1');
        $this->addSql('ALTER TABLE notifications CHANGE message message LONGTEXT NOT NULL, CHANGE etat etat VARCHAR(255) NOT NULL, CHANGE userId userId INT DEFAULT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D364B64DCC FOREIGN KEY (userId) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX userid ON notifications');
        $this->addSql('CREATE INDEX IDX_6000B0D364B64DCC ON notifications (userId)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT notifications_ibfk_1 FOREIGN KEY (userId) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_1');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_2');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_1');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY order_ibfk_2');
        $this->addSql('ALTER TABLE `order` CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE payment_method payment_method VARCHAR(255) NOT NULL, CHANGE exact_address exact_address LONGTEXT NOT NULL, CHANGE ordered_at ordered_at DATETIME NOT NULL, CHANGE total_price total_price NUMERIC(10, 2) NOT NULL');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993981AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (cart_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX cart_id ON `order`');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F52993981AD5CDBF ON `order` (cart_id)');
        $this->addSql('DROP INDEX user_id ON `order`');
        $this->addSql('CREATE INDEX IDX_F5299398A76ED395 ON `order` (user_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_1 FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY fk_user');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_1');
        $this->addSql('DROP INDEX reference ON product');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY fk_user');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY product_ibfk_1');
        $this->addSql('ALTER TABLE product CHANGE id_user id_user INT DEFAULT NULL, CHANGE name name VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE category category VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (stock_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX stock_id ON product');
        $this->addSql('CREATE INDEX IDX_D34A04ADDCD6110 ON product (stock_id)');
        $this->addSql('DROP INDEX fk_user ON product');
        $this->addSql('CREATE INDEX IDX_D34A04AD6B3CA4B ON product (id_user)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_1 FOREIGN KEY (stock_id) REFERENCES stock (stock_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE publications DROP FOREIGN KEY publications_ibfk_1');
        $this->addSql('ALTER TABLE publications DROP FOREIGN KEY publications_ibfk_1');
        $this->addSql('ALTER TABLE publications CHANGE description description LONGTEXT DEFAULT NULL, CHANGE publication_date publication_date DATETIME NOT NULL, CHANGE statut statut VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE publications ADD CONSTRAINT FK_32783AF46B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX id_user ON publications');
        $this->addSql('CREATE INDEX IDX_32783AF46B3CA4B ON publications (id_user)');
        $this->addSql('ALTER TABLE publications ADD CONSTRAINT publications_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY reports_ibfk_1');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY reports_ibfk_2');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY reports_ibfk_1');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY reports_ibfk_2');
        $this->addSql('ALTER TABLE reports CHANGE description description LONGTEXT DEFAULT NULL, CHANGE report_date report_date DATETIME NOT NULL, CHANGE status status VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA7456B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA74538B217A7 FOREIGN KEY (publication_id) REFERENCES publications (publication_id)');
        $this->addSql('DROP INDEX id_user ON reports');
        $this->addSql('CREATE INDEX IDX_F11FA7456B3CA4B ON reports (id_user)');
        $this->addSql('DROP INDEX publication_id ON reports');
        $this->addSql('CREATE INDEX IDX_F11FA74538B217A7 ON reports (publication_id)');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT reports_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT reports_ibfk_2 FOREIGN KEY (publication_id) REFERENCES publications (publication_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY fk_user_stock');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY fk_user_stock');
        $this->addSql('ALTER TABLE stock CHANGE id_user id_user INT DEFAULT NULL, CHANGE last_update last_update DATETIME NOT NULL');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656606B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('DROP INDEX fk_user_stock ON stock');
        $this->addSql('CREATE INDEX IDX_4B3656606B3CA4B ON stock (id_user)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT fk_user_stock FOREIGN KEY (id_user) REFERENCES user (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX email ON user');
        $this->addSql('DROP INDEX username ON user');
        $this->addSql('ALTER TABLE user CHANGE last_name last_name VARCHAR(255) NOT NULL, CHANGE first_name first_name VARCHAR(255) NOT NULL, CHANGE username username VARCHAR(255) NOT NULL, CHANGE email email VARCHAR(255) NOT NULL, CHANGE numTel numTel VARCHAR(255) NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED52B4B97');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEE45655E');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDED52B4B97');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEE45655E');
        $this->addSql('ALTER TABLE booking CHANGE id_event id_event INT NOT NULL, CHANGE id_location id_location INT NOT NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_1 FOREIGN KEY (id_event) REFERENCES event (id_event) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT booking_ibfk_2 FOREIGN KEY (id_location) REFERENCES location (id_location) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_e00ceddee45655e ON booking');
        $this->addSql('CREATE INDEX id_location ON booking (id_location)');
        $this->addSql('DROP INDEX idx_e00cedded52b4b97 ON booking');
        $this->addSql('CREATE INDEX id_event ON booking (id_event)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDED52B4B97 FOREIGN KEY (id_event) REFERENCES event (id_event)');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEE45655E FOREIGN KEY (id_location) REFERENCES location (id_location)');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7A76ED395');
        $this->addSql('ALTER TABLE cart DROP FOREIGN KEY FK_BA388B7A76ED395');
        $this->addSql('ALTER TABLE cart CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE total_price total_price NUMERIC(10, 2) DEFAULT \'0.00\'');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT cart_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_ba388b7a76ed395 ON cart');
        $this->addSql('CREATE INDEX user_id ON cart (user_id)');
        $this->addSql('ALTER TABLE cart ADD CONSTRAINT FK_BA388B7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE cart_product MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY FK_2890CCAA1AD5CDBF');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY FK_2890CCAA4584665A');
        $this->addSql('DROP INDEX `PRIMARY` ON cart_product');
        $this->addSql('ALTER TABLE cart_product DROP FOREIGN KEY FK_2890CCAA4584665A');
        $this->addSql('ALTER TABLE cart_product DROP id, CHANGE quantity quantity INT DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT cart_product_ibfk_1 FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT cart_product_ibfk_2 FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cart_product ADD PRIMARY KEY (cart_id, product_id)');
        $this->addSql('DROP INDEX idx_2890ccaa4584665a ON cart_product');
        $this->addSql('CREATE INDEX product_id ON cart_product (product_id)');
        $this->addSql('ALTER TABLE cart_product ADD CONSTRAINT FK_2890CCAA4584665A FOREIGN KEY (product_id) REFERENCES product (product_id)');
        $this->addSql('ALTER TABLE code_promo CHANGE code_promo code_promo VARCHAR(20) NOT NULL, CHANGE date_creation date_creation DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX code_promo ON code_promo (code_promo)');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A38B217A7');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A6B3CA4B');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A38B217A7');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A6B3CA4B');
        $this->addSql('ALTER TABLE comments CHANGE content content TEXT NOT NULL, CHANGE comment_date comment_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_1 FOREIGN KEY (publication_id) REFERENCES publications (publication_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_2 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_5f9e962a6b3ca4b ON comments');
        $this->addSql('CREATE INDEX id_user ON comments (id_user)');
        $this->addSql('DROP INDEX idx_5f9e962a38b217a7 ON comments');
        $this->addSql('CREATE INDEX publication_id ON comments (publication_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A38B217A7 FOREIGN KEY (publication_id) REFERENCES publications (publication_id)');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA76B3CA4B');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY FK_3BAE0AA76B3CA4B');
        $this->addSql('ALTER TABLE event CHANGE id_user id_user INT NOT NULL, CHANGE description description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT event_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_3bae0aa76b3ca4b ON event');
        $this->addSql('CREATE INDEX id_user ON event (id_user)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA76B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE location CHANGE city city VARCHAR(50) NOT NULL, CHANGE status status VARCHAR(50) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE dimension dimension VARCHAR(50) NOT NULL, CHANGE price price NUMERIC(10, 2) NOT NULL, CHANGE has_3d_tour has_3d_tour TINYINT(1) DEFAULT 0, CHANGE table_set_count table_set_count INT DEFAULT 3, CHANGE include_corner_plants include_corner_plants TINYINT(1) DEFAULT 1, CHANGE window_style window_style VARCHAR(50) DEFAULT \'Modern\', CHANGE door_style door_style VARCHAR(50) DEFAULT \'Modern\', CHANGE include_ceiling_lights include_ceiling_lights TINYINT(1) DEFAULT 1, CHANGE light_color light_color VARCHAR(50) DEFAULT \'#FFFF00\'');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY FK_6000B0D364B64DCC');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY FK_6000B0D364B64DCC');
        $this->addSql('ALTER TABLE notifications CHANGE message message TEXT NOT NULL, CHANGE etat etat VARCHAR(50) NOT NULL, CHANGE userId userId INT NOT NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT notifications_ibfk_1 FOREIGN KEY (userId) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_6000b0d364b64dcc ON notifications');
        $this->addSql('CREATE INDEX userId ON notifications (userId)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D364B64DCC FOREIGN KEY (userId) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993981AD5CDBF');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F52993981AD5CDBF');
        $this->addSql('ALTER TABLE `order` DROP FOREIGN KEY FK_F5299398A76ED395');
        $this->addSql('ALTER TABLE `order` CHANGE status status VARCHAR(255) DEFAULT \'PENDING\', CHANGE payment_method payment_method VARCHAR(50) NOT NULL, CHANGE exact_address exact_address TEXT NOT NULL, CHANGE ordered_at ordered_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE total_price total_price NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_1 FOREIGN KEY (cart_id) REFERENCES cart (cart_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT order_ibfk_2 FOREIGN KEY (user_id) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_f52993981ad5cdbf ON `order`');
        $this->addSql('CREATE UNIQUE INDEX cart_id ON `order` (cart_id)');
        $this->addSql('DROP INDEX idx_f5299398a76ed395 ON `order`');
        $this->addSql('CREATE INDEX user_id ON `order` (user_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F52993981AD5CDBF FOREIGN KEY (cart_id) REFERENCES cart (cart_id)');
        $this->addSql('ALTER TABLE `order` ADD CONSTRAINT FK_F5299398A76ED395 FOREIGN KEY (user_id) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADDCD6110');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD6B3CA4B');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADDCD6110');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD6B3CA4B');
        $this->addSql('ALTER TABLE product CHANGE id_user id_user INT NOT NULL, CHANGE name name VARCHAR(100) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE category category VARCHAR(30) NOT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES user (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT product_ibfk_1 FOREIGN KEY (stock_id) REFERENCES stock (stock_id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX reference ON product (reference)');
        $this->addSql('DROP INDEX idx_d34a04addcd6110 ON product');
        $this->addSql('CREATE INDEX stock_id ON product (stock_id)');
        $this->addSql('DROP INDEX idx_d34a04ad6b3ca4b ON product');
        $this->addSql('CREATE INDEX fk_user ON product (id_user)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (stock_id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD6B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE publications DROP FOREIGN KEY FK_32783AF46B3CA4B');
        $this->addSql('ALTER TABLE publications DROP FOREIGN KEY FK_32783AF46B3CA4B');
        $this->addSql('ALTER TABLE publications CHANGE description description TEXT DEFAULT NULL, CHANGE publication_date publication_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE statut statut VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE publications ADD CONSTRAINT publications_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_32783af46b3ca4b ON publications');
        $this->addSql('CREATE INDEX id_user ON publications (id_user)');
        $this->addSql('ALTER TABLE publications ADD CONSTRAINT FK_32783AF46B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY FK_F11FA7456B3CA4B');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY FK_F11FA74538B217A7');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY FK_F11FA7456B3CA4B');
        $this->addSql('ALTER TABLE reports DROP FOREIGN KEY FK_F11FA74538B217A7');
        $this->addSql('ALTER TABLE reports CHANGE description description TEXT DEFAULT NULL, CHANGE report_date report_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE status status VARCHAR(255) DEFAULT \'Pending\' NOT NULL');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT reports_ibfk_1 FOREIGN KEY (id_user) REFERENCES user (id_user) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT reports_ibfk_2 FOREIGN KEY (publication_id) REFERENCES publications (publication_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_f11fa7456b3ca4b ON reports');
        $this->addSql('CREATE INDEX id_user ON reports (id_user)');
        $this->addSql('DROP INDEX idx_f11fa74538b217a7 ON reports');
        $this->addSql('CREATE INDEX publication_id ON reports (publication_id)');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA7456B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE reports ADD CONSTRAINT FK_F11FA74538B217A7 FOREIGN KEY (publication_id) REFERENCES publications (publication_id)');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656606B3CA4B');
        $this->addSql('ALTER TABLE stock DROP FOREIGN KEY FK_4B3656606B3CA4B');
        $this->addSql('ALTER TABLE stock CHANGE id_user id_user INT NOT NULL, CHANGE last_update last_update DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT fk_user_stock FOREIGN KEY (id_user) REFERENCES user (id_user) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_4b3656606b3ca4b ON stock');
        $this->addSql('CREATE INDEX fk_user_stock ON stock (id_user)');
        $this->addSql('ALTER TABLE stock ADD CONSTRAINT FK_4B3656606B3CA4B FOREIGN KEY (id_user) REFERENCES user (id_user)');
        $this->addSql('ALTER TABLE user CHANGE last_name last_name VARCHAR(100) NOT NULL, CHANGE first_name first_name VARCHAR(100) NOT NULL, CHANGE username username VARCHAR(50) NOT NULL, CHANGE email email VARCHAR(150) NOT NULL, CHANGE numTel numTel VARCHAR(20) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX email ON user (email)');
        $this->addSql('CREATE UNIQUE INDEX username ON user (username)');
    }
}
