# config/routes.yaml

# Toutes les routes passent par ce préfixe langue : /fr/... ou /en/...
app:
    resource: '../src/Controller/'
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: 'fr|en'

# Redirection automatique de / vers /fr
home_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /fr
        permanent: false
