services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\PublicationTranslationService:
        arguments:
            $logger: '@monolog.logger.translation'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\AyaCartExtension:
        tags: ['twig.extension']