# config/services.yaml
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/profile_images'
    recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha_secret_key: '%env(RECAPTCHA_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Extension Twig existante
    App\Twig\AyaCartExtension:
        tags: ['twig.extension']

    